name: Push to AWS CodeCommit Mirror

on:
  push:
    branches:
      - '*'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Push to AWS CodeCommit
        run: |
          git remote add codecommit https://git-codecommit.us-east-1.amazonaws.com/v1/repos/shamansharif-minimalist-cv
          git push --mirror codecommit
